### ISSUE TITLE
Password recovery is problematic.

### ISSUE THREAD

**Issue by jasonm23** [nex3/marmalade#7]
There's a couple of issues with password recovery, 
- Recovery emails get caught by google mail's spambot, I can't speak for other providers. and I'm not sure how we'd get around this one, but making email confirmation part of the initial sign up (or maybe just documenting the possibility in context, for the password recovery pages, and the initial sign up / registration loop.) 
- Resetting the password from the temporary key is only possible via the REST api, which will take even Emacs users a few head scratching moments, personally I had to go scour the `server.js` source code to figure this out.  (hey, who doesn't love a puzzle?)
- When you do get the temporary password, it's done in a way that looks like you need to press the recover button again, but maybe that's just me being dumb. - in essence the display says the email was sent, and a button to send it again is shown. (I suppose combined with the spam catching, events conspire to confuse.)

FYI, this process was kicked off for me by inexplicably having duplicate accounts, I can't guarantee I hadn't done anything stupid, because perhaps I did, but I will just flag that here, if the same issue pops up again, ... you know, for stats.

**Comment by nicferrier** [comment]
Hi, this repo is dead now. I have taken over marmalade and the repo is http://github.com/nicferrier/elmarmalade

**Comment by jasonm23** [comment]
Thank you Nic
